version: "3.7"
services:
  app:
    build: ./django
    volumes:
      - ./django/src:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
  
  db:
    image: postgres:10.5
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
      - POSTGRES_DB=todo_db
